### ISSUE TITLE
could you give other client example using callback to receive message from server?

### ISSUE THREAD

**Issue by verystrongjoe** [ilkerkesen/tornado-websocket-client-example#1]
could you give other client example using callback to receive message from server?

I changed it in your source code but it didn't work.  others is ok. 

Thanks in advance!

**Comment by ilkerkesen** [comment]
@verystrongjoe I don't understand what you mean. Could you pleaese give a concrete explanation? Though, run method in client should be enough to receive messages from websocket server.
