### ISSUE TITLE
The io_loop call argument has no longer works

### ISSUE THREAD

**Issue by holadepo** [ilkerkesen/tornado-websocket-client-example#2]
The io_loop call argument for PeriodicCallback has been removed from version 5.0 of tornado, so line 16 of client.py should now be:

`PeriodicCallback(self.keep_alive, 20000).start()`

instead of:

`PeriodicCallback(self.keep_alive, 20000, io_loop=self.ioloop).start()`

**Comment by ilkerkesen** [comment]
@holadepo could you fix it and open a PR? I'm not developing projects by using Tornado nowadays.

**Comment by holadepo** [comment]
@ilkerkesen I did that already. It is the only pull request for the repository.
